### ISSUE TITLE
README.md update needed for lookup function config

### ISSUE THREAD

**Issue by bhayes-zd** [arsmn/fiber-casbin#2]
## Details
Howdy there 👋 Friendly heads up that it looks like the function to perform a lookup within the `fibercasbin` config was changed to actually use the field `Lookup` rather than `SubLookupFn`. In case anyone else runs into the same issue, wanted to give the heads up to update that line in the docs. 😄 

> README.md 
```go
 SubLookupFn: func(c *fiber.Ctx) string {
          // fetch authenticated user subject
 }
```

> Fixed reference
```go
 Lookup: func(c *fiber.Ctx) string {
          // fetch authenticated user subject
  }
```

**Comment by arsmn** [comment]
Hello there
Thanks for your consideration. I've updated the docs.
