### ISSUE TITLE
What do you think about support for route params

### ISSUE THREAD

**Issue by AchoArnold** [arsmn/fiber-casbin#3]
Hello 

Take the following code for example 

```go
 app.Delete("/blog/:id",
    authz.RequiresPermissions([]string{"blog:create", "blog:delete"}, fibercasbin.AtLeastOne),
    func(c *fiber.Ctx) error {
      // your handler
    },
  )
```

I may want to set up the permission such that I would love to actually check if the user has the role to delete the blog post with id "123". Is that something you plan to support?

**Comment by arsmn** [comment]
Hi @AchoArnold 
You can use [RoutePermission](https://github.com/arsmn/fiber-casbin#routepermission) or if you have better idea, you are welcome to send PR

**Comment by maansiii** [comment]
`app.get("/auth/google/app", 
  passport.authenticate('google', { failureRedirect: "/login" }),
  function(req, res) {
    res.redirect('/app');
  });`

This is for Google Authentication^ using O'Auth'2
