### ISSUE TITLE
How to update casbin Rules When i AddPolicy/RemovePolicy

### ISSUE THREAD

**Issue by cleveng** [arsmn/fiber-casbin#5]
Hey...

```
func IndexTest(ctx *fiber.Ctx) error {

	return ctx.Status(http.StatusOK).JSON("hello world！")
}

func IndexDemo1(ctx *fiber.Ctx) error {
	enforcer := config.Enforcer
	if ok, _ := enforcer.AddPolicy("admin", "/v1/test", "GET"); !ok {
		return ctx.Status(http.StatusOK).JSON("Policy exist")
	}
	return ctx.Status(http.StatusOK).JSON("add success")
}

func IndexDemo2(ctx *fiber.Ctx) error {
	enforcer := config.Enforcer
	if ok, _ := enforcer.RemovePolicy("admin", "/v1/test", "GET"); !ok {
		return ctx.Status(http.StatusOK).JSON("Policy no exist")
	}
	return ctx.Status(http.StatusOK).JSON("delete success")
}
```
And the CasbinMiddleware code like this:
```
func Casbin() *fibercasbin.CasbinMiddleware {
	db := config.DB
	adapter, _ := gormadapter.NewAdapterByDBWithCustomTable(db, &models.CasbinRule{})
	authz := fibercasbin.New(fibercasbin.Config{
		ModelFilePath: "config/rbac_model.conf",
		PolicyAdapter: adapter,
		Unauthorized: func(c *fiber.Ctx) error {
			return c.Status(http.StatusUnauthorized).JSON(fiber.Map{"message": "Unauthorized...", "status_code": 401})
		},
		Forbidden: func(c *fiber.Ctx) error {
			return c.Status(http.StatusNotFound).JSON(fiber.Map{"message": "Forbidden ...", "status_code": 404})
		},
		Lookup: func(c *fiber.Ctx) string {
			// get subject from BasicAuth, JWT, Cookie etc in real world
			return "admin"
		},
	})
	//adapter.LoadPolicy() // model Model 
	return authz
}
```
test the method Demo1 or Demo2 , the CasbinMiddleware not immediate effect。

```
v.Get("/test", authz.RoutePermission(), IndexTest)
```
Can your help？

**Comment by hsluoyz** [comment]
@svcg did your adapter support/enable the AutoSave feature? https://casbin.org/docs/en/adapters#autosave

**Comment by cleveng** [comment]
```
var Enforcer *casbin.Enforcer

func InitCasbin() {
       // DB is gorm global db connect
	adapter, _ := gormadapter.NewAdapterByDBWithCustomTable(DB, &models.CasbinRule{})
	Enforcer, _ = casbin.NewEnforcer("config/rbac_model.conf", adapter)
	Enforcer.EnableAutoSave(true)
}
```
Even i set the option of the AutoSave, not anything happen。
When i run the main code again， the rule is effect。

**Comment by hsluoyz** [comment]
@svcg can you provide a full example, like a Golang repo at GitHub, so we can reproduce your error?

**Comment by cleveng** [comment]
> @svcg can you provide a full example, like a Golang repo at GitHub, so we can reproduce your error?

https://github.com/svcg/-fiber_casbin_demo

**Comment by hsluoyz** [comment]
@closetool

**Comment by kilosonc** [comment]
@svcg I guess I know the reason.
![image](https://user-images.githubusercontent.com/52988625/112148287-a88f4f00-8c18-11eb-8816-ccbe9ab21ce0.png)
![image](https://user-images.githubusercontent.com/52988625/112148420-d4aad000-8c18-11eb-8f2c-117a79cce750.png)
As you can see here, you used one casbin instance for add/update, another for authrizing, so your changes will not be synced between two instances.
In this case, you should write middleware on your own

**Comment by cleveng** [comment]
> @svcg I guess I know the reason.
> ![image](https://user-images.githubusercontent.com/52988625/112148287-a88f4f00-8c18-11eb-8816-ccbe9ab21ce0.png)
> ![image](https://user-images.githubusercontent.com/52988625/112148420-d4aad000-8c18-11eb-8f2c-117a79cce750.png)
> As you can see here, you used one casbin instance for add/update, another for authrizing, so your changes will not be synced between two instances.
> In this case, you should write middleware on your own

en. If i change the `https://github.com/arsmn/fiber-casbin/blob/master/main.go` struct
```
// CasbinMiddleware ...
type CasbinMiddleware struct {
	config   Config
	Enforcer *casbin.Enforcer  //change that code 
}
```
Then i don't use config.InitCasbin() , and the add method changed likes that :
```
func Add(ctx *fiber.Ctx) error {
	//enforcer := config.Enforcer // before code
	authz := middlewares.Casbin() // new code  authz.Enforcer
	authz.Enforcer.LoadPolicy()  
	if ok, _ := 	authz.Enforcer.AddPolicy("admin", "/v1/test", "GET"); !ok { 
		return ctx.Status(http.StatusOK).JSON("Policy exist")
	}
	return ctx.Status(http.StatusOK).JSON("add success")
}
```
no effect //https://github.com/svcg/-fiber_casbin_demo.git

**Comment by kilosonc** [comment]
@svcg 
![image](https://user-images.githubusercontent.com/52988625/112282903-8520de80-8cc2-11eb-8eb1-46e24be411b2.png)
Your code got many errors, I can't run it.

**Comment by arsmn** [comment]
Hi @svcg 
Please upgrade to v2.7.0.
Thanks to @suleymanozev you can use your own Enforcer to fix the issue.

**Comment by cleveng** [comment]
> Hi @svcg
> Please upgrade to v2.7.0.
> Thanks to @suleymanozev you can use your own Enforcer to fix the issue.

Hi, I use the new version and fix the issue.
```
authz := fibercasbin.New(fibercasbin.Config{
		Enforcer: config.Enforcer,
		Mode: fibercasbin.ModeEnforcer,
		ModelFilePath: "config/rbac_model.conf",
		PolicyAdapter: adapter,
	})
```
I think the `Enforcer`、`PolicyAdapter`、`ModelFilePath`，can be simple init.

And `https://github.com/svcg/-fiber_casbin_demo.git` is using `gorm v1.20` example code , you can add that into readme.

**Comment by hsluoyz** [comment]
@arsmn

**Comment by arsmn** [comment]
Hi @svcg 
Thank you for your recommendation. I've updated the initialization and `FiberCasbinMode` is removed.
You can set your own `Enforcer` or `ModelFilePath` and `PolicyAdapter` to init the middleware.
Your `Gorm` example is also added to readme.
